export const titles = [
  'The Fallen',
  'Fallen Heroes',
  'White Bread',
  'Spicy Meatball',
  'Zeus',
  'Poseidon',
  'Demeter',
  'Ares',
  'Athena',
  'Apollo',
  'Artemis',
  'Mighty Aphrodite',
  'Hermes',
  'Dionysus',
  'Hades',
  'Nike',
  'Nemesis',
  'Iris',
  'Hecate',
  'Tyche',
  'Rainbow Sprinkles',
  'Hashtag This Sux',
  'Birdshit',
  'Heaven & Hell',
  'Word Up',
  'Holy Water',
  'Banana Split',
];
